export const LOADING_INGREDIENTS = "LOADING_INGREDIENTS";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const ERROR_ON_FETCH_INGREDIENTS = "ERROR_ON_FETCH_INGREDIENTS";

export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";


export const SET_ORDERS = "SET_ORDERS";


export const ORDER_STARTED_PUSHING = "ORDER_STARTED_PUSHING";
export const ORDER_WAS_PUSHED = "ORDER_WAS_PUSHED";
export const RESET_PUSHED_STATE = "RESET_PUSHED_STATE";
export const ERROR_ON_PUSH_ORDER = "ERROR_ON_PUSH_ORDER";


export const LOG_IN_STARTED = "LOG_IN_STARTED";
export const LOG_IN_FAILED = "LOG_IN_FAILED";
export const LOG_IN_PASSED = "LOG_IN_PASSED";
export const LOG_OUT = "LOG_OUT";


export const SIGN_UP_STARTED = "SIGN_UP_STARTED";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";
export const SIGN_UP_PASSED = "SIGN_UP_PASSED";

export const RESET_AUTH = "RESET_AUTH";